### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by thanone2** [elad335/rpcs3#17]
### Quick summary

Is an android port on the roadmap? or is it unlikely?

### Details

If possible, maybe it could have bluetooth controller support and also touch controls. Obviously it would be like 15 fps, and low quality textures. I think this would be great for mostly 2d fighting games and the such.

**Comment by elad335** [comment]
idk and Im not sure why you post here.

**Comment by thanone2** [comment]
this was my suggestion for rpcs3.
